export const organizations = [
  "BX Coding",
  "Play and Learn Lab",
  "Independent",
  "Honeywell",
  "The Technique",
  "Wreck Techs GT",
];
export const tags = ["Build", "Design", "Learn", "Research", "Teach", "Write"];
export const skills = [
  "Docker",
  "Git",
  "HTML",
  "JavaScript",
  "LaTeX",
  "Node.js",
  "Python",
  "React",
  "SQL",
  "Verilog",
  "Pyodide",
  "Airflow",
  "AWS",
  "Typescript",
  "Firebase",
  "Java",
  "TailwindCSS",
  "Figma",
  "Next.js",
  "SvelteKit",
  "Langchain",
  "React",
  "Material UI",
];
